### ISSUE TITLE
struct unpacking size error

### ISSUE THREAD

**Issue by Jieship** [JRBANCEL/Chromagnon#1]
Hello,

At chromagnon/cacheEntry.py:68, you have

struct.unpack('L', block.read(8))[0]

Python throws an error here because the struct.unpack expects 4 bytes from 'L'.
I believe what you want is 'Q'.
Your code works fine with that fix.

All the best,
Jie

**Comment by JRBANCEL** [comment]
Thank you for noticing the error.
I am curious why Python never threw any exception and correctly parsed the bytes even if the parameter was incorrect.
Which version of Python are you using?
