### ISSUE TITLE
chromagnonTab.py 

### ISSUE THREAD

**Issue by davidhq** [JRBANCEL/Chromagnon#2]
Hi,

I want to parse my Tabs but cannot find that file...

Wiki says:
`python chromagnonTab.py ~/.config/chromium/Default/Current\ Tabs`

Please help, 
thank you

**Comment by JRBANCEL** [comment]
On which platform are you working?
The location of this file is different on each operating system or even different Linux distributions.
On Windows, it is **"%HOMEPATH%\AppData\Local\Google\Chrome\User Data\Default\Current Tabs"**.
Also, note that I haven't update the tool in years. The format of the file might have changed.

**Comment by davidhq** [comment]
Actually I cannot find `chromagnonTab.py` in your repo...

And yes I also think the format has changed because on other tool I tried is broken (as well?)...

**Comment by JRBANCEL** [comment]
It is in the SNSS branch: https://github.com/JRBANCEL/Chromagnon/tree/SNSS

**Comment by davidhq** [comment]
Thank you...

it kind of works... I get some output, but it's strange:

`python chromagnonTab.py Current\ Tabs`:

```
$ python chromagnonTab.py Current\ Tabs 
SelectedNavigationInTab - Tab: 82, Index: 1, Time: 13068137311581068
UpdateTabNavigation - Tab: 82, Index: 0, Url: chrome://newtab/
UpdateTabNavigation - Tab: 82, Index: 1, Url: https://kobra.io/#/e/-Jb6TvM1aiyNhU0_zdTY
SelectedNavigationInTab - Tab: 83, Index: 0, Time: 13068137428197904
UpdateTabNavigation - Tab: 83, Index: 0, Url: http://localhost/elgg/?XDEBUG_SESSION_START=12514
SelectedNavigationInTab - Tab: 84, Index: 0, Time: 13068141337923901
UpdateTabNavigation - Tab: 84, Index: 0, Url: http://localhost/elgg/?XDEBUG_SESSION_START=10708
SelectedNavigationInTab - Tab: 85, Index: 6, Time: 13068141884171523
UpdateTabNavigation - Tab: 85, Index: 3, Url: http://localhost/elgg/groups/profile/42219/loop/tab/42222
UpdateTabNavigation - Tab: 85, Index: 4, Url: http://localhost/elgg/groups/edit/42219
UpdateTabNavigation - Tab: 85, Index: 5, Url: http://localhost/elgg/groups/member/admin
UpdateTabNavigation - Tab: 85, Index: 6, Url: http://localhost/elgg/groups/add/35
UpdateTabNavigation - Tab: 85, Index: 7, Url: http://localhost/elgg/groups/profile/42234/loop/tab/42237
UpdateTabNavigation - Tab: 85, Index: 8, Url: http://localhost/elgg/groups/edit/42234
...
```

I mostly get this one url (localhost/elff) (135 lines of it)... so these are not currently open tabs...

Strange that it doesn't fail with an error but returns this... Is this to be expected because maybe the format changed? Thank you

**Comment by JRBANCEL** [comment]
On my machine, this file (Current Tabs) is only written when the browser is closed.
You can easily verify that by checking when it was modified for the last time.
This means that what you see is what was in your browser the last time you closed it, not the current state.

**Comment by davidhq** [comment]
Sure... Actually this is a file from last week after the browser was closed.

So the script unf. doesn't work as intended
