### ISSUE TITLE
Deobfuscate Visited Links file

### ISSUE THREAD

**Issue by Bluscream** [JRBANCEL/Chromagnon#7]
Hey, i would love to have a tool to get the visited links from it's file.

**Comment by JRBANCEL** [comment]
It is not possible. As explained [here](https://github.com/JRBANCEL/Chromagnon/wiki/ChromagnonVisitedLinks-=-chromagnonVisitedLinks.py), the visited links feature is implemented as a hash table. [Hashing](https://en.wikipedia.org/wiki/Hash_function) is a one way operation. It is only possible to find out if a given URL has been visited, but not to enumerate the visited URLs.

**Comment by Bluscream** [comment]
damn, okay thanks :)
